library(tmctools)

test_that("idAssetGroup() works", {
  expect_equal(idAssetGroup(NA)                        , as.character(NA))
  expect_equal(idAssetGroup("4K DT 5")                 , "4K")
  expect_equal(idAssetGroup("AC-7")                    , "AC")
  expect_equal(idAssetGroup("ADMIN")                   , "ADMIN")
  expect_equal(idAssetGroup("GEN ADMIN")               , "ADMIN")
  expect_equal(idAssetGroup("ADT-1")                   , "AD")
  # TODO: ARMOR VEHICLE
  expect_equal(idAssetGroup("ATV-1")                   , "AT")
  expect_equal(idAssetGroup("CIP XX")                  , "CIP")
  expect_equal(idAssetGroup("CKDI DT-034")             , "CKDI")
  expect_equal(idAssetGroup("CM 2")                    , "CM")
  expect_equal(idAssetGroup("CONCRETE MIXER 2")        , "CM")
  expect_equal(idAssetGroup("CONCRETE MIXR 2")         , "CM")
  expect_equal(idAssetGroup("CONCRETE MXER 3")         , "CM")
  expect_equal(idAssetGroup("CT 15")                   , "CT")
  expect_equal(idAssetGroup("YBBM 28")                 , "DM")
  expect_equal(idAssetGroup("YBM 96")                  , "DM")
  expect_equal(idAssetGroup("219")                     , "DT")
  expect_equal(idAssetGroup("ALL VOLVO DT'S")          , "DT")
  expect_equal(idAssetGroup("DST 195")                 , "DT")
  expect_equal(idAssetGroup("DT 101")                  , "DT")
  expect_equal(idAssetGroup("DT-107 (SAMLPLE STAND)")  , "DT")
  expect_equal(idAssetGroup("EQ 101")                  , "EQ")
  expect_equal(idAssetGroup("FASCRAFT 1")              , "FC")
  expect_equal(idAssetGroup("FAST CRAFT")              , "FC")
  expect_equal(idAssetGroup("forklift 2")              , "FL")
  expect_equal(idAssetGroup("FRL 1")                   , "FL")
  expect_equal(idAssetGroup("MFL 2")                   , "FL")
  expect_equal(idAssetGroup("FT 5")                    , "FR")
  expect_equal(idAssetGroup("FLY SQUID")               , "FS")
  expect_equal(idAssetGroup("FV VI")                   , "FS")
  expect_equal(idAssetGroup("FL 5")                    , "FT")
  expect_equal(idAssetGroup("FTR 5")                   , "FM")
  expect_equal(idAssetGroup("GEN SET")                 , "GS")
  expect_equal(idAssetGroup("GENERATOR")               , "GS")
  expect_equal(idAssetGroup("GS 5 XX")                 , "GS")
  expect_equal(idAssetGroup("GS-35 (ENVI/ BOTANICAL)") , "GS")
  expect_equal(idAssetGroup("GS-49 (COVID-19)")        , "GS")
  expect_equal(idAssetGroup("DT - 238")                , "HDT")
  expect_equal(idAssetGroup("DT - 239")                , "HDT")
  expect_equal(idAssetGroup("DT - 240")                , "HDT")
  expect_equal(idAssetGroup("DT - 249")                , "HDT")
  expect_equal(idAssetGroup("HPK DT 1")                , "HPK")
  expect_equal(idAssetGroup("LCT TMC-3")               , "LC")
  expect_equal(idAssetGroup("BRGY")                    , "LGU")
  expect_equal(idAssetGroup("LAWN MOER")               , "LM")
  expect_equal(idAssetGroup("LAWN MOWER")              , "LM")
  expect_equal(idAssetGroup("LM 1")                    , "LM")
  expect_equal(idAssetGroup("LWN MOWER 4")             , "LM")
  expect_equal(idAssetGroup("MOER 3")                  , "LM")
  expect_equal(idAssetGroup("Crusher")                 , "MC")
  expect_equal(idAssetGroup("MOBILE CRUSH-1")          , "MC")
  expect_equal(idAssetGroup("MOBILE CRUSR-1")          , "MC")
  expect_equal(idAssetGroup("MOBILE CRUSER")           , "MC")
  expect_equal(idAssetGroup("MDT 1")                   , "MD")
  expect_equal(idAssetGroup("MDDT 1")                  , "MD")
  expect_equal(idAssetGroup("MIZPEH SV-1")             , "MIZPEH")
  expect_equal(idAssetGroup("Marketing")               , "MKTG")
  expect_equal(idAssetGroup("MANLIFT-1")               , "ML")
  expect_equal(idAssetGroup("ML 5")                    , "ML")
  expect_equal(idAssetGroup("MTEL SV-01")              , "MTEL")
  expect_equal(idAssetGroup("MC")                      , "MR")
  expect_equal(idAssetGroup("MC 1 MC 2")               , "MR")
  expect_equal(idAssetGroup("MOTORCYCLE")              , "MR")
  expect_equal(idAssetGroup("MOTORCYCLE-4")            , "MR")
  expect_equal(idAssetGroup("MOBILE SCREEN")           , "MS")
  expect_equal(idAssetGroup("MOBILE SCREENER")         , "MS")
  expect_equal(idAssetGroup("MOBILE SCRENR")           , "MS")
  expect_equal(idAssetGroup("MOS")                     , "MS")
  expect_equal(idAssetGroup("MS-1")                    , "MS")
  expect_equal(idAssetGroup("SCREENER")                , "MS")
  expect_equal(idAssetGroup("SCRENIR 1")               , "MS")
  expect_equal(idAssetGroup("MT 5")                    , "MT")
  expect_equal(idAssetGroup("MT 5 GT 21")              , "MT")
  expect_equal(idAssetGroup("MWL 5")                   , "MW")
  expect_equal(idAssetGroup("MTX-1")                   , "MX")
  expect_equal(idAssetGroup("MTX-2 (MINI TX-2)")       , "MX")
  expect_equal(idAssetGroup("NB DT 5")                 , "NBI")
  expect_equal(idAssetGroup("NBC DT 5")                , "NBI")
  expect_equal(idAssetGroup("NBI NDT-005")             , "NBI")
  expect_equal(idAssetGroup("NC DT 5")                 , "NBI")
  expect_equal(idAssetGroup("COMREL NCIP VEHICLE")     , "NCIP")
  expect_equal(idAssetGroup("PACE XX")                 , "PACE")
  expect_equal(idAssetGroup("Patrolboat")              , "PATROLBOAT")
  expect_equal(idAssetGroup("Pumpboat")                , "PB")
  expect_equal(idAssetGroup("PMT-1")                   , "PM")
  expect_equal(idAssetGroup("POALRIS DT-090110")       , "POLARIS")
  expect_equal(idAssetGroup("POLARIS DT RAM-530")      , "POLARIS")
  expect_equal(idAssetGroup("R6 11")                   , "RG")
  expect_equal(idAssetGroup("RG 15")                   , "RG")
  expect_equal(idAssetGroup("SB 15")                   , "SB")
  expect_equal(idAssetGroup("SDMC DT 15")              , "SDMC")
  expect_equal(idAssetGroup("SMDC DT 15")              , "SDMC")
  expect_equal(idAssetGroup("Security")                , "SECURITY")
  expect_equal(idAssetGroup("SKAFF DT 15")             , "SKAFF")
  expect_equal(idAssetGroup("SMCC")                    , "SMCC")
  expect_equal(idAssetGroup("SMCC 01-MANLIFT")         , "SMCC")
  expect_equal(idAssetGroup("ST 96")                   , "ST")
  expect_equal(idAssetGroup("SP-44 (COVID-19)")        , "SV")
  expect_equal(idAssetGroup("SP-63 NAC SUR")           , "SV")
  expect_equal(idAssetGroup("SP 96")                   , "SV")
  expect_equal(idAssetGroup("TACOPHIL")                , "TACOPHIL")
  expect_equal(idAssetGroup("TWL 96")                  , "TL")
  expect_equal(idAssetGroup("TRGC TL 96")              , "TRGC")
  expect_equal(idAssetGroup("TX 96")                   , "TX")
  expect_equal(idAssetGroup("V-4")                     , "VR")
  expect_equal(idAssetGroup("VC 96")                   , "VR")
  expect_equal(idAssetGroup("WL 96")                   , "WL")
  expect_equal(idAssetGroup("WM 96")                   , "WM")
  expect_equal(idAssetGroup("WP 96")                   , "WP")
  expect_equal(idAssetGroup("CRANE 1")                 , "WR")
  expect_equal(idAssetGroup("WC 1")                    , "WR")
  expect_equal(idAssetGroup("WTL 96")                  , "WT")
  expect_equal(idAssetGroup("WLT 96")                  , "WT")
  expect_equal(idAssetGroup("WX 96")                   , "WX")
  expect_equal(idAssetGroup("ASSAY CRUSHER")           , "ZZZ")
  expect_equal(idAssetGroup("BADMINTON")               , "ZZZ")
  expect_equal(idAssetGroup("GSI")                     , "ZZZ")
  expect_equal(idAssetGroup("JAW CRUSHER")             , "ZZZ")
  expect_equal(idAssetGroup("MDTC BLDG")               , "ZZZ")
  expect_equal(idAssetGroup("POWER ELCT'L")            , "ZZZ")
  expect_equal(idAssetGroup("ROLLER CRUSHER")          , "ZZZ")
  expect_equal(idAssetGroup("SAMPLE PREP CRUSHER")     , "ZZZ")
  expect_equal(idAssetGroup("TRAFFIC SHD AID")         , "ZZZ")
  expect_equal(idAssetGroup("XXX")                     , "ZZZ")
})

rm(list = ls())
