# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify asset group
#'
#' Identifies the asset group of a given equipment (or entity) which is the
#'   recipient of the item withdrawn from warehouse.
#'   This data can be seen from warehouse issuance slips.
#'
#'   Below are the identified groups:
#'   \itemize{
#'   \item Contractors
#'     \describe{
#'     \item{4K}{4K Development Corporation}
#'     \item{HPK}{HPK Construction}
#'     \item{NBI}{Nickelbase Incorporated}
#'     \item{PACE}{PrinceAce Corporation}
#'     \item{POLARIS}{Polaris Construction & General Services}
#'     \item{SDMC}{Southernphil Development and Marketing Corporation (FITZ-SDMC)}
#'     \item{SKAFF}{SKAFF Construkt Incorporated}
#'     \item{SMCC}{Sumitomo-Mitsui Construction Company}
#'     \item{TACOPHIL}{}
#'     \item{TRGC}{Tango Romeo General Construction}
#'     }
#'   \item Equipment
#'     \describe{
#'     \item{ADT}{articulated dump truck}
#'     \item{ATV}{all-terrain vehicle}
#'     \item{CM}{concrete mixer}
#'     \item{CT}{bulldozer}
#'     \item{DT}{dump truck}
#'     \item{FASTCRAFT}{}
#'     \item{FL}{fuel lorry}
#'     \item{FORKLIFT}{}
#'     \item{FS}{flying squid}
#'     \item{FT}{fire truck}
#'     \item{FTR}{farm tractors}
#'     \item{GS}{power generator set}
#'     \item{GT}{garbage truck}
#'     \item{HDT}{HOWO dump truck}
#'     \item{LM}{lawn mower}
#'     \item{MC}{motorcycle}
#'     \item{MDT}{mini dump truck}
#'     \item{ML}{man lift}
#'     \item{MOC}{mobile crusher}
#'     \item{MOS}{mobile screener}
#'     \item{MT}{maintenance truck}
#'     \item{MTX}{mini tracked excavator}
#'     \item{MWL}{mini wheeled pay loader}
#'     \item{PATROLBOAT}{}
#'     \item{PB}{pump boat}
#'     \item{PMT}{prime mover truck}
#'     \item{RG}{road grader}
#'     \item{SB}{service bus}
#'     \item{SP}{service pickup}
#'     \item{ST}{service truck}
#'     \item{TL}{tracked pay loader}
#'     \item{TWL}{tower light}
#'     \item{TX}{tracked excavator}
#'     \item{VC}{vibrating compactor}
#'     \item{WC}{wheeled crane}
#'     \item{WL}{wheeled pay loader}
#'     \item{WM}{welding machine}
#'     \item{WP}{water pump}
#'     \item{WT}{water tank}
#'     \item{WTL}{water lorry}
#'     \item{WX}{wheeled excavator}
#'     \item{YBM}{Yoshida Boring Machine}
#'     }
#'   \item Fixed assets
#'     \describe{
#'     \item{ADMIN}{Admin building}
#'     \item{EQ}{Engineer's Quarters}
#'     \item{CIP}{construction in-progress}
#'     }
#'   \item Other parties
#'     \describe{
#'     \item{LGU}{local government unit}
#'     \item{MKTG}{marketing}
#'     \item{SECURITY}{}
#'     }
#'   \item Unknown
#'     \itemize{
#'     \item ZZZ
#'     }
#'   }
#'
#' @param x a character vector representing the equipment
#' @return a character vector representing the asset group
#' @export
idAssetGroup <- function(x) {
    .Call('_tmctools_idAssetGroup', PACKAGE = 'tmctools', x)
}

#' Read Surpac DTM file
#'
#' Reads a valid DTM file. It is assumed that both the DTM and String files
#'   are present in the same directory and have the same file name. Outputs
#'   a data.frane with each row representing a triangle of the DTM.
#'
#' @param dtmFile file name
#' @param srid spatial reference identifier
#' @return a data.frame with the following columns:
#'   \describe{
#'     \item{polygon}{polygon in ewkt or wkt format}
#'     \item{edge_length}{length of the longest edge}
#'     \item{slope_angle}{angle in radians between z-axis and the polygon normal}
#'   }
#' @export
readDTM <- function(dtmFile, srid = "") {
    .Call('_tmctools_readDTM', PACKAGE = 'tmctools', dtmFile, srid)
}

#' Read PLY File
#'
#' Reads the ply file created in \link{updateInsituSurface}.
#'
#' @param plyFile file name
#' @return a data.frame with the following columns:
#'   \describe{
#'     \item{polygon}{polygon in ewkt or wkt format}
#'     \item{edge_length}{length of the longest edge}
#'     \item{slope_angle}{angle in radians between z-axis and the polygon normal}
#'   }
#' @export
readPlyText <- function(plyFile) {
    .Call('_tmctools_readPlyText', PACKAGE = 'tmctools', plyFile)
}

#' Write Surpac DTM file
#'
#' Reads a valid DTM file and writes it into PostGIS. It is assumed that the
#'   PostGIS user has its pgpass set-up.
#'
#' It is also assumed that a table with access to a sequence is set-up like
#'   the \code{sql} query below:
#'   \preformatted{
#' CREATE SEQUENCE sequence_name
#' INCREMENT 1
#' START 1
#' MINVALUE 1
#' MAXVALUE 9223372036854775807
#' CACHE 1;
#'
#' CREATE TABLE table_name
#' (
#'   id integer NOT NULL DEFAULT nextval('sequence_name'::regclass),
#'   edge_length double precision,
#'   geom geometry(PolygonZ,3125),
#'   CONSTRAINT table_name_pkey PRIMARY KEY (id)
#' )}
#'
#' @param dtmFile file name
#' @param user PostGIS user
#' @param hostname PostGIS server host name or IP address
#' @param dbname database to write into
#' @param tableName table to write into
#' @param schema schema to write into
#' @param port port number to connect to at the server host, or socket file
#'   name extension for Unix-domain connections
#' @param srid spatial reference identifier
#' @return number of rows uploaded to the table
#' @export
writeDTM <- function(dtmFile, user, hostname, dbname, tableName, schema = "staging", port = "5432", srid = "3125") {
    .Call('_tmctools_writeDTM', PACKAGE = 'tmctools', dtmFile, user, hostname, dbname, tableName, schema, port, srid)
}

