# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Export Surface to a PLY File
#'
#' A polygon soup represented by a PostGIS table with a PolygonZ column 'geom'
#'   is exported into a Stanford Polygon File (*.ply). During exportation, a
#'   table will be created in the default schema. Thus, if the user has no
#'   privilege to write on the default schema, exporting will fail.
#'
#' @param db_user PostGIS user
#' @param db_host PostGIS server host name or IP address
#' @param db_name database containing the polygon soup
#' @param schema schema containing the polygon soup
#' @param db_table table containing the polygon soup
#' @param srid spatial reference identifier of the geometry
#' @param port port number to connect to at the server host, or socket file
#'   name extension for Unix-domain connections
#' @param digits precision in number of decimal digits
#' @param binary output binary file or not (ASCII)
#' @return file name of exported ply file
#' @export
exportPly <- function(db_user, db_host, db_name, schema, db_table, srid = "3125", port = "5432", digits = 3L, binary = FALSE) {
    .Call('_tmctools_exportPly', PACKAGE = 'tmctools', db_user, db_host, db_name, schema, db_table, srid, port, digits, binary)
}

#' Identify asset group
#'
#' Identifies the asset group of a given equipment (or entity) which is the
#'   recipient of the item withdrawn from warehouse.
#'   This data can be seen from warehouse issuance slips prior to
#'   implementation of SAP.
#'
#'   Below are the identified groups:
#'   \itemize{
#'   \item Contractors
#'     \describe{
#'     \item{4K}{4K Development Corporation}
#'     \item{CKDI}{Cagdianao Konstruct Development Incorporated}
#'     \item{HPK}{HPK Construction}
#'     \item{MIZPEH}{}
#'     \item{MTEL}{}
#'     \item{NBI}{Nickelbase Incorporated}
#'     \item{PACE}{PrinceAce Corporation}
#'     \item{POLARIS}{Polaris Construction & General Services}
#'     \item{SDMC}{Southernphil Development and Marketing Corporation (FITZ-SDMC)}
#'     \item{SKAFF}{SKAFF Construkt Incorporated}
#'     \item{SMCC}{Sumitomo-Mitsui Construction Company}
#'     \item{TACOPHIL}{}
#'     \item{TRGC}{Tango Romeo General Construction}
#'     }
#'   \item Equipment
#'     \describe{
#'     \item{AC}{air compressor}
#'     \item{AD}{articulated dump truck}
#'     \item{AT}{all-terrain vehicle}
#'     \item{CM}{concrete mixer}
#'     \item{CT}{bulldozer}
#'     \item{DM}{Drill Machine}
#'     \item{DT}{dump truck}
#'     \item{FC}{fast craft}
#'     \item{FL}{forklift}
#'     \item{FT}{fuel truck}
#'     \item{FM}{farm tractors}
#'     \item{FR}{fire truck}
#'     \item{FS}{flying squid}
#'     \item{GS}{power generator set}
#'     \item{GT}{garbage truck}
#'     \item{HDT}{HOWO dump truck}
#'     \item{LC}{landing craft tank}
#'     \item{LM}{lawn mower}
#'     \item{MC}{mobile crusher}
#'     \item{MD}{mini dump truck}
#'     \item{ML}{man lift}
#'     \item{MR}{motorcycle}
#'     \item{MS}{mobile screener}
#'     \item{MT}{maintenance truck}
#'     \item{MX}{mini tracked excavator}
#'     \item{MW}{mini wheeled pay loader}
#'     \item{PATROLBOAT}{}
#'     \item{PB}{pump boat}
#'     \item{PM}{prime mover truck}
#'     \item{RG}{road grader}
#'     \item{SB}{service bus}
#'     \item{ST}{service truck}
#'     \item{SV}{service car}
#'     \item{TL}{tower light}
#'     \item{TX}{tracked excavator}
#'     \item{VR}{vibrating compactor}
#'     \item{WL}{wheeled pay loader}
#'     \item{WM}{welding machine}
#'     \item{WP}{water pump}
#'     \item{WR}{wheeled crane}
#'     \item{WT}{water truck}
#'     \item{WX}{wheeled excavator}
#'     }
#'   \item Fixed assets
#'     \describe{
#'     \item{ADMIN}{Admin building}
#'     \item{EQ}{Engineer's Quarters}
#'     \item{CIP}{construction in-progress}
#'     }
#'   \item Other parties
#'     \describe{
#'     \item{LGU}{local government unit}
#'     \item{MKTG}{marketing}
#'     \item{NCIP}{National Commission on Indigenous Peoples}
#'     \item{SECURITY}{}
#'     }
#'   \item Unknown
#'     \itemize{
#'     \item ZZZ
#'     }
#'   }
#'
#' @param x a character vector representing the equipment
#' @return a character vector representing the asset group
#' @export
idAssetGroup <- function(x) {
    .Call('_tmctools_idAssetGroup', PACKAGE = 'tmctools', x)
}

#' Write binary PLY to database
#'
#' Reads the binary PLY file and writes it to a PostGIS database via streaming.
#' The table will have the columns: \code{geom geometry(PolygonZ, srid)} and
#' \code{slope_angle double precision}.
#'
#'
#' @param ply name of ply file to be translated
#' @param db_user PostGIS user
#' @param db_host PostGIS server host name or IP address
#' @param db_name database to write into
#' @param db_table table to write into. This will be overwritten if it exists!
#' @param schema schema to write into
#' @param port port number to connect to at the server host, or socket file
#'   name extension for Unix-domain connections
#' @param srid spatial reference identifier
#' @return void
#' @export
plyBinToDB <- function(ply, db_user, db_host, db_name, db_table, schema = "public", port = "5432", srid = "3125") {
    invisible(.Call('_tmctools_plyBinToDB', PACKAGE = 'tmctools', ply, db_user, db_host, db_name, db_table, schema, port, srid))
}

#' Translate Binary PLY File
#'
#' Translates a binary PLY file to ASCII format.
#'
#' @param in_ply name of ply file to be translated
#' @param out_ply name of output ply file
#' @return void
#' @export
plyBinToText <- function(in_ply, out_ply = "text.ply") {
    invisible(.Call('_tmctools_plyBinToText', PACKAGE = 'tmctools', in_ply, out_ply))
}

#' Read Surpac DTM file
#'
#' Reads a valid DTM file. It is assumed that both the DTM and String files
#'   are present in the same directory and have the same file name. Outputs
#'   a data.frame with each row representing a triangle of the DTM.
#'
#' @param dtm file name
#' @param srid spatial reference identifier
#' @return a data.frame with the following columns:
#'   \describe{
#'     \item{area_2d}{2D area of the polygon}
#'     \item{edge_length}{length of the longest edge}
#'     \item{slope_angle}{angle in radians between z-axis and the polygon normal}
#'     \item{polygon}{polygon in ewkt or wkt format}
#'   }
#' @export
readDTM <- function(dtm, srid = "") {
    .Call('_tmctools_readDTM', PACKAGE = 'tmctools', dtm, srid)
}

#' Read PLY File
#'
#' Reads the ply an covert it to a data frame.
#'
#' @param ply file name
#' @param srid spatial reference identifier of the geometry if output is ewkt
#' @return a data.frame with the following columns:
#'   \describe{
#'     \item{area_2d}{2D area of the polygon}
#'     \item{edge_length}{length of the longest edge}
#'     \item{slope_angle}{angle in radians between z-axis and the polygon normal}
#'     \item{polygon}{polygon in ewkt or wkt format}
#'   }
#' @export
readPly <- function(ply, srid = "") {
    .Call('_tmctools_readPly', PACKAGE = 'tmctools', ply, srid)
}

#' Write Surpac DTM file
#'
#' Reads a valid DTM file and writes it into PostGIS. It is assumed that the
#'   PostGIS user has its pgpass set-up.
#'
#' It is also assumed that a table with access to a sequence is set-up like
#'   the \code{sql} query below:
#'   \preformatted{
#' CREATE SEQUENCE sequence_name
#' INCREMENT 1
#' START 1
#' MINVALUE 1
#' MAXVALUE 9223372036854775807
#' CACHE 1;
#'
#' CREATE TABLE table_name
#' (
#'   id integer NOT NULL DEFAULT nextval('sequence_name'::regclass),
#'   edge_length double precision,
#'   geom geometry(PolygonZ,3125),
#'   CONSTRAINT table_name_pkey PRIMARY KEY (id)
#' )}
#'
#' @param dtm file name
#' @param db_user PostGIS user
#' @param db_host PostGIS server host name or IP address
#' @param db_name database to write into
#' @param db_table table to write into
#' @param schema schema to write into
#' @param port port number to connect to at the server host, or socket file
#'   name extension for Unix-domain connections
#' @param srid spatial reference identifier
#' @return number of rows uploaded to the table
#' @export
writeDTM <- function(dtm, db_user, db_host, db_name, db_table, schema = "staging", port = "5432", srid = "3125") {
    .Call('_tmctools_writeDTM', PACKAGE = 'tmctools', dtm, db_user, db_host, db_name, db_table, schema, port, srid)
}

